name: End-to-end tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Dependencies
        run: npm i
        
      - name: Start Server 
        uses: cypress-io/github-action@v3
        with:  
          build: npm build
          start: npm start
          wait-on: "http://localhost:3000"
        env:
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.COMMERCE_PROVIDER }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.COMMERCE_PROVIDER }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.COMMERCE_PROVIDER }}
          
          
      
      - name: Run Cypress Tests
        run: npm run cypress:run
