name: End-to-end tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Start Server 
        uses: cypress-io/github-action@v3
        with:  
          build: npm run build
          start: npm start
          wait-on: "http://localhost:3000"
        env:
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}

      - name: Upload Video
        uses: actions/upload-artifact@v2
        with:
          name: cypress-videos
          path: /home/runner/work/FitFinder/FitFinder/cypress/videos/
        if: always()
        

